//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionRH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process_salida_empleado
    {
        public string Empleado { get; set; }
        public string Tipo_de_salida { get; set; }
        public string Motivo { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Id { get; set; }
    }
}
