//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionRH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process_Vacaciones
    {
        public string Empleado { get; set; }
        public System.DateTime desde { get; set; }
        public System.DateTime hasta { get; set; }
        public System.DateTime correspondiente { get; set; }
        public string comentario { get; set; }
        public int Id { get; set; }
    }
}
